# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioCommucation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioCommucation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x41udioCommucation.proto\",\n\x08PairInfo\x12\x10\n\x08Identity\x18\x01 \x01(\x08\x12\x0e\n\x06PairID\x18\x02 \x01(\t\"1\n\tSessionID\x12\x11\n\tVaildPair\x18\x03 \x01(\x08\x12\x11\n\tSessionID\x18\x04 \x01(\t\"=\n\x11StartModelRequest\x12\x10\n\x08ModelNum\x18\x05 \x01(\x05\x12\x16\n\x0e\x41\x64\x64itionalInfo\x18\x06 \x01(\t\"E\n\tAudioData\x12\n\n\x02No\x18\t \x01(\x05\x12\x16\n\x0e\x41\x64\x64itionalInfo\x18\n \x01(\t\x12\x14\n\x0c\x41udioRawData\x18\x0b \x03(\x05\"G\n\x11RecognitionResult\x12\n\n\x02No\x18\x0c \x01(\x05\x12\x16\n\x0e\x41\x64\x64itionalInfo\x18\r \x01(\t\x12\x0e\n\x06Result\x18\x0e \x01(\t\"6\n\x0c\x43loseRequest\x12\x13\n\x0bShouldClose\x18\x0f \x01(\x08\x12\x11\n\tCloseInfo\x18\x10 \x01(\t\"(\n\x0eGetDataRequest\x12\x16\n\x0e\x41\x64\x64itionalInfo\x18\x11 \x01(\t\";\n\x0eStatusResponse\x12\x11\n\tIsSuccess\x18\x12 \x01(\x08\x12\x16\n\x0e\x41\x64\x64itionalInfo\x18\x13 \x01(\t\"&\n\x0c\x45mptyRequest\x12\x16\n\x0e\x41\x64\x64itionalInfo\x18\x14 \x01(\t2\xf4\x03\n\rRouterService\x12\"\n\x07GetPair\x12\t.PairInfo\x1a\n.SessionID\"\x00\x12\x31\n\x08SetModel\x12\x12.StartModelRequest\x1a\x0f.StatusResponse\"\x00\x12\x31\n\nP_GetModel\x12\r.EmptyRequest\x1a\x12.StartModelRequest\"\x00\x12\x34\n\x10P_SetModeSuccess\x12\x0f.StatusResponse\x1a\r.EmptyRequest\"\x00\x12\x30\n\x08SendData\x12\n.AudioData\x1a\x12.RecognitionResult\"\x00(\x01\x30\x01\x12,\n\tP_GetData\x12\x0f.GetDataRequest\x1a\n.AudioData\"\x00\x30\x01\x12\x35\n\x0cP_SendResult\x12\x12.RecognitionResult\x1a\x0f.StatusResponse\"\x00\x12)\n\x05\x43lose\x12\r.CloseRequest\x1a\x0f.StatusResponse\"\x00\x12,\n\nP_GetClose\x12\r.EmptyRequest\x1a\r.CloseRequest\"\x00\x12\x33\n\x11P_SendCloseResult\x12\r.CloseRequest\x1a\r.EmptyRequest\"\x00\x62\x06proto3'
)




_PAIRINFO = _descriptor.Descriptor(
  name='PairInfo',
  full_name='PairInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Identity', full_name='PairInfo.Identity', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PairID', full_name='PairInfo.PairID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=70,
)


_SESSIONID = _descriptor.Descriptor(
  name='SessionID',
  full_name='SessionID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='VaildPair', full_name='SessionID.VaildPair', index=0,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SessionID', full_name='SessionID.SessionID', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=121,
)


_STARTMODELREQUEST = _descriptor.Descriptor(
  name='StartModelRequest',
  full_name='StartModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ModelNum', full_name='StartModelRequest.ModelNum', index=0,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AdditionalInfo', full_name='StartModelRequest.AdditionalInfo', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=184,
)


_AUDIODATA = _descriptor.Descriptor(
  name='AudioData',
  full_name='AudioData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='No', full_name='AudioData.No', index=0,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AdditionalInfo', full_name='AudioData.AdditionalInfo', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AudioRawData', full_name='AudioData.AudioRawData', index=2,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=255,
)


_RECOGNITIONRESULT = _descriptor.Descriptor(
  name='RecognitionResult',
  full_name='RecognitionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='No', full_name='RecognitionResult.No', index=0,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AdditionalInfo', full_name='RecognitionResult.AdditionalInfo', index=1,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Result', full_name='RecognitionResult.Result', index=2,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=328,
)


_CLOSEREQUEST = _descriptor.Descriptor(
  name='CloseRequest',
  full_name='CloseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ShouldClose', full_name='CloseRequest.ShouldClose', index=0,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CloseInfo', full_name='CloseRequest.CloseInfo', index=1,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=384,
)


_GETDATAREQUEST = _descriptor.Descriptor(
  name='GetDataRequest',
  full_name='GetDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AdditionalInfo', full_name='GetDataRequest.AdditionalInfo', index=0,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=426,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='IsSuccess', full_name='StatusResponse.IsSuccess', index=0,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AdditionalInfo', full_name='StatusResponse.AdditionalInfo', index=1,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=487,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AdditionalInfo', full_name='EmptyRequest.AdditionalInfo', index=0,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=527,
)

DESCRIPTOR.message_types_by_name['PairInfo'] = _PAIRINFO
DESCRIPTOR.message_types_by_name['SessionID'] = _SESSIONID
DESCRIPTOR.message_types_by_name['StartModelRequest'] = _STARTMODELREQUEST
DESCRIPTOR.message_types_by_name['AudioData'] = _AUDIODATA
DESCRIPTOR.message_types_by_name['RecognitionResult'] = _RECOGNITIONRESULT
DESCRIPTOR.message_types_by_name['CloseRequest'] = _CLOSEREQUEST
DESCRIPTOR.message_types_by_name['GetDataRequest'] = _GETDATAREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PairInfo = _reflection.GeneratedProtocolMessageType('PairInfo', (_message.Message,), {
  'DESCRIPTOR' : _PAIRINFO,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:PairInfo)
  })
_sym_db.RegisterMessage(PairInfo)

SessionID = _reflection.GeneratedProtocolMessageType('SessionID', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONID,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:SessionID)
  })
_sym_db.RegisterMessage(SessionID)

StartModelRequest = _reflection.GeneratedProtocolMessageType('StartModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTMODELREQUEST,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:StartModelRequest)
  })
_sym_db.RegisterMessage(StartModelRequest)

AudioData = _reflection.GeneratedProtocolMessageType('AudioData', (_message.Message,), {
  'DESCRIPTOR' : _AUDIODATA,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:AudioData)
  })
_sym_db.RegisterMessage(AudioData)

RecognitionResult = _reflection.GeneratedProtocolMessageType('RecognitionResult', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONRESULT,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:RecognitionResult)
  })
_sym_db.RegisterMessage(RecognitionResult)

CloseRequest = _reflection.GeneratedProtocolMessageType('CloseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEREQUEST,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:CloseRequest)
  })
_sym_db.RegisterMessage(CloseRequest)

GetDataRequest = _reflection.GeneratedProtocolMessageType('GetDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDATAREQUEST,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:GetDataRequest)
  })
_sym_db.RegisterMessage(GetDataRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'AudioCommucation_pb2'
  # @@protoc_insertion_point(class_scope:EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)



_ROUTERSERVICE = _descriptor.ServiceDescriptor(
  name='RouterService',
  full_name='RouterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=530,
  serialized_end=1030,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPair',
    full_name='RouterService.GetPair',
    index=0,
    containing_service=None,
    input_type=_PAIRINFO,
    output_type=_SESSIONID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetModel',
    full_name='RouterService.SetModel',
    index=1,
    containing_service=None,
    input_type=_STARTMODELREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='P_GetModel',
    full_name='RouterService.P_GetModel',
    index=2,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_STARTMODELREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='P_SetModeSuccess',
    full_name='RouterService.P_SetModeSuccess',
    index=3,
    containing_service=None,
    input_type=_STATUSRESPONSE,
    output_type=_EMPTYREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='RouterService.SendData',
    index=4,
    containing_service=None,
    input_type=_AUDIODATA,
    output_type=_RECOGNITIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='P_GetData',
    full_name='RouterService.P_GetData',
    index=5,
    containing_service=None,
    input_type=_GETDATAREQUEST,
    output_type=_AUDIODATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='P_SendResult',
    full_name='RouterService.P_SendResult',
    index=6,
    containing_service=None,
    input_type=_RECOGNITIONRESULT,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='RouterService.Close',
    index=7,
    containing_service=None,
    input_type=_CLOSEREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='P_GetClose',
    full_name='RouterService.P_GetClose',
    index=8,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_CLOSEREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='P_SendCloseResult',
    full_name='RouterService.P_SendCloseResult',
    index=9,
    containing_service=None,
    input_type=_CLOSEREQUEST,
    output_type=_EMPTYREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTERSERVICE)

DESCRIPTOR.services_by_name['RouterService'] = _ROUTERSERVICE

# @@protoc_insertion_point(module_scope)
